#!/bin/bash
#SBATCH -J FastX_quality #Name for your job
#SBATCH -n 1 #Number of tasks when using MPI. Default is 1.
#SBATCH -c 1 #Number of cores requested. Default is 1.
#SBATCH -N 1 #Number of nodes to spread cores across-
